version: '3.3'
services:
  database:
    image: mysql
    container_name: grocery-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grocery
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

